apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet # 一個模板產生多個 Application
metadata:
  name: argocd
  namespace: infra
spec:
  generators:
  - list:
      elements:
      - env: dev
        envDir: DEV
      - env: stg
        envDir: STG
      - env: prod
        envDir: PROD

  template:
    # 以下 {{env}} 會被上面的值取代
    metadata:
      name: 'argocd-{{env}}'
      namespace: infra
    spec:
      project: default # ArgoCD 預設專案
      source:
        repoURL: https://github.com/zxcbig7/Deployment-Apps.git
        targetRevision: HEAD
        path: 'mydevweb-fe/{{envDir}}'
        helm:
          releaseName: 'argocd-{{env}}'
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc # 代表 ArgoCD 自己的 Kubernetes API Server
        namespace: '{{env}}' # 部署到同名 namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
