apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-cluster
spec:
  provider:
    vault:
      server: "http://vault.infra.svc.cluster.local:8200"
      path: "kv-infra"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: infra
