apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-pull-secret
  namespace: prod
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: harbor-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"harbor.viclai.idv.tw":{"username":"{{ .username }}","password":"{{ .password }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: harbor-robot
        property: username
    - secretKey: password
      remoteRef:
        key: harbor-robot
        property: password
