apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: infra
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.15.1
    helm:
      releaseName: harbor
      values: |
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: secret
            secret:
              secretName: "harbor-tls"
          ingress:
            hosts:
              core: harbor.viclai.idv.tw
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
        externalURL: https://harbor.viclai.idv.tw
        existingSecretAdminPassword: harbor-admin-secret
        existingSecretAdminPasswordKey: adminPassword
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              size: 5Gi
            database:
              size: 1Gi
            redis:
              size: 1Gi
        trivy:
          enabled: false
        notary:
          enabled: false
        core:
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
        portal:
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
        jobservice:
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
        registry:
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
        database:
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
        redis:
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
