apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: infra
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: database
        property: password
