apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: infra
spec:
  provider:
    vault:
      server: "http://vault.infra.svc.cluster.local:8200"
      path: "kv-infra"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
