apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: infra
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.29.1
    helm:
      releaseName: vault
      valueFiles: []
      values: |
        server:
          standalone:
            enabled: true
            config: |
              ui = true
              listener "tcp" {
                tls_disable = 1
                address     = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "file" {
                path = "/vault/data"
              }
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: vault.viclai.idv.tw
                paths:
                  - /
          dataStorage:
            enabled: true
            size: 1Gi
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
        ui:
          enabled: true
          serviceType: ClusterIP
        injector:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
